config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new'
  get '/articles/:id', to: 'articles#show', as: :article
  post '/articles', to: 'articles#create'
  get '/articles/:id/edit', to: 'articles#edit', as: :edit_article
  patch '/articles/:id', to: 'articles#update'
  delete '/articles/:id', to: 'articles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(articles_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(articles_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def articles_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= form_for(@article) do |a| %>
  <%= a.label :title %>
  <%= a.text_field :title %>
  <%= a.label :content %>
  <%= a.text_field :content %>
  <%= a.submit %>
<% end %>

<%= link_to articles_path do %>
  <i class="fas fa-backward"> Back to all articles</i>
<% end %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <h2><%= link_to article.title, article_path(article) %></h2>
      <p><%= article.content %></p>

    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for(@article) do |a| %>
  <%= a.label :title %>
  <%= a.text_field :title %>
  <%= a.label :content %>
  <%= a.text_field :content %>
  <%= a.submit %>
<% end %>

<br> <%# not good practice %>

<%= link_to articles_path do %>
  <i class="fas fa-backward"> Back to all articles</i>
<% end %>

app/views/articles/show.html.erb
<%= link_to edit_article_path do %> <i class="fas fa-edit"></i> <% end %> | <%= link_to article_path(@article), method: :delete,
            data: { confirm: "Are you sure you want to delete the task: #{@article.title}?" } do %>
            <i class="fas fa-trash-alt"></i>
            <% end %>

<h1><%= @article.title %> </h1>
<p><%= @article.content %></p>

<%= link_to articles_path do %>
  <i class="fas fa-backward"> Back to all articles</i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to "New article", articles_new_path%>
      </li>
    </ul>
    <%= yield %>
  </div>
  </body>
</html>